name: Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Node 12.x Environment
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ secrets.BACKEND_FUNCTIONAPP_NAME }}
        package: ./
        publish-profile: ${{ secrets.BACKEND_PUBLISH_PROFILE }}
