export const {
  // AAD_TENANT_DOMAIN,
  AZURE_MEDIA_SERVICES_ACCOUNT_NAME: accountName,
  // AZURE_MEDIA_SERVICES_LOCATION,
  AZURE_MEDIA_SERVICES_RESOURCE_GROUP: resourceGroup,
  AZURE_MEDIA_SERVICES_SUBSCRIPTION: subscription,
  // ARM_AAD_AUDIENCE,
  // ARM_ENDPOINT,
  AZURE_MEDIA_SERVICES_STREAM_ENDPOINT: streamEndpoint,
} = process.env;
